#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const VERSION = "3.5.0";
const CLAUDE_SKILLS_DIR = ".claude/skills";
const AGENTS_SKILLS_DIR = ".agents/skills";
const MARKER_START = "<!-- relay-workflow:start -->";
const MARKER_END = "<!-- relay-workflow:end -->";

const RELAY_SKILLS = [
  "relay-analyze",
  "relay-auto",
  "relay-brainstorm",
  "relay-cleanup",
  "relay-design",
  "relay-discover",
  "relay-exercise",
  "relay-exercise-auto",
  "relay-exercise-file",
  "relay-exercise-run",
  "relay-help",
  "relay-new-issue",
  "relay-notebook",
  "relay-order",
  "relay-plan",
  "relay-resolve",
  "relay-review",
  "relay-scan",
  "relay-setup",
  "relay-superplan",
  "relay-verify",
];

function copyDirRecursive(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function generateRelaySection() {
  return `${MARKER_START}
<!-- Auto-generated by relay-workflow. Edits between markers will be overwritten on install. -->
## Relay Workflow Skills

Relay gives AI coding agents persistent memory of what was built, what broke,
and what's next. Skills are in \`.agents/skills/relay-*/\`.

| Skill | Purpose |
|-------|---------|
| /relay-setup | Initialize Relay in a new project |
| /relay-scan | Generate project status |
| /relay-order | Prioritize work |
| /relay-discover | Scan codebase for issues |
| /relay-new-issue | File a specific bug or gap |
| /relay-brainstorm | Explore a feature idea |
| /relay-design | Design features from brainstorm |
| /relay-cleanup | Archive stale brainstorms |
| /relay-exercise | Map project capabilities for stress-testing |
| /relay-exercise-run | Execute scenarios against a capability |
| /relay-exercise-file | Walk findings and file issues or brainstorm seeds |
| /relay-exercise-auto | Auto-sweep run + file across the active session |
| /relay-analyze | Validate item before implementation |
| /relay-plan | Create implementation plan |
| /relay-superplan | Create plan via 5 competing agents |
| /relay-review | Adversarial review of plan |
| /relay-verify | Verify implementation |
| /relay-notebook | Verification notebook |
| /relay-resolve | Close out and archive |
| /relay-auto | Auto-walk the full code pipeline across items |
| /relay-help | Navigate the workflow |

Start with \`/relay-setup\`, then \`/relay-help\`.

Workflow: \`/relay-analyze\` → \`/relay-plan\` or \`/relay-superplan\` → \`/relay-review\` → implement → \`/relay-verify\` → \`/relay-notebook\` → \`/relay-resolve\`

Exercise flow: \`/relay-exercise\` → \`/relay-exercise-run\` → \`/relay-exercise-file\` → (filed items flow into normal code pipeline)

Auto-sweep: \`/relay-exercise-auto\` runs the run+file pair end-to-end across the active session, with one isolated agent per work item.

Code auto-pipeline: \`/relay-auto\` drives items from \`relay-ordering.md\` through the full code pipeline (analyze → plan/superplan → review → implement → verify → resolve) — one isolated agent per item, resumable across context compaction.

Goal mode: \`/relay-exercise "<your goal>"\` builds a top-down journey of required capabilities and discovers missing ones as gaps.
${MARKER_END}`;
}

function appendContextFile(targetDir, fileName) {
  const filePath = path.join(targetDir, fileName);
  const section = generateRelaySection();

  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, section + "\n", "utf8");
    return "created";
  }

  const content = fs.readFileSync(filePath, "utf8");
  const startIdx = content.indexOf(MARKER_START);

  if (startIdx !== -1) {
    const endIdx = content.indexOf(MARKER_END, startIdx);
    if (endIdx !== -1) {
      // Check if existing section was modified
      const oldSection = content.substring(startIdx, endIdx + MARKER_END.length);
      if (oldSection !== section) {
        console.warn(`  Warning: ${fileName} relay section content differs from current version — overwriting`);
      }
      const before = content.substring(0, startIdx);
      const after = content.substring(endIdx + MARKER_END.length);
      fs.writeFileSync(filePath, before + section + after, "utf8");
      return "updated";
    }
    // Start marker found but no end marker — don't modify
    console.warn(`  Warning: Found start marker but no end marker in ${fileName}, skipping update`);
    return "skipped";
  }

  // Append to existing file
  const separator = content.endsWith("\n") ? "\n" : "\n\n";
  fs.writeFileSync(filePath, content + separator + section + "\n", "utf8");
  return "appended";
}

function removeContextSection(targetDir, fileName) {
  const filePath = path.join(targetDir, fileName);

  if (!fs.existsSync(filePath)) {
    return;
  }

  const content = fs.readFileSync(filePath, "utf8");
  const startIdx = content.indexOf(MARKER_START);

  if (startIdx === -1) {
    return; // No relay section
  }

  const endIdx = content.indexOf(MARKER_END, startIdx);
  if (endIdx === -1) {
    console.warn(`  Warning: Found start marker but no end marker in ${fileName}, skipping removal`);
    return;
  }

  let before = content.substring(0, startIdx);
  let after = content.substring(endIdx + MARKER_END.length);

  // Trim extra blank lines around the removed block
  before = before.replace(/\n+$/, "");
  after = after.replace(/^\n+/, "");

  const result = before && after ? before + "\n\n" + after : (before + after).trim();

  if (!result) {
    fs.unlinkSync(filePath);
    return;
  }

  fs.writeFileSync(filePath, result + "\n", "utf8");
}

function install(targetDir) {
  const skillsSrc = path.join(__dirname, "..", CLAUDE_SKILLS_DIR);
  const claudeDest = path.join(targetDir, CLAUDE_SKILLS_DIR);
  const agentsDest = path.join(targetDir, AGENTS_SKILLS_DIR);

  // Refuse if install target resolves to the source skills directory.
  // Without this, fs.rmSync(dest) inside the install loop would delete
  // the source before copyDirRecursive runs, silently destroying the
  // working tree. Only claudeDest can collide (agentsDest uses a
  // different leaf), so a single equality check is sufficient.
  if (path.resolve(claudeDest) === path.resolve(skillsSrc)) {
    console.error(`\n  Error: install target resolves to the source skills directory (${path.resolve(skillsSrc)}).\n  Refusing to install — this would delete the source. Use a different target directory.\n`);
    process.exit(1);
  }

  // Verify source skills exist
  if (!fs.existsSync(skillsSrc)) {
    console.error("Error: Relay skills not found in package. Reinstall with: npm install relay-workflow");
    process.exit(1);
  }

  // Create both skill directories in target
  for (const dest of [claudeDest, agentsDest]) {
    try {
      fs.mkdirSync(dest, { recursive: true });
    } catch (err) {
      console.error(`\n  Error: Cannot create ${dest}\n  ${err.message}\n`);
      process.exit(1);
    }
  }

  // Copy each relay skill to both directories
  let installed = 0;
  let skipped = 0;

  for (const skill of RELAY_SKILLS) {
    const src = path.join(skillsSrc, skill);

    if (!fs.existsSync(src)) {
      console.warn(`  Warning: ${skill} not found in package, skipping`);
      skipped++;
      continue;
    }

    for (const destBase of [claudeDest, agentsDest]) {
      const dest = path.join(destBase, skill);

      if (fs.existsSync(dest)) {
        fs.rmSync(dest, { recursive: true, force: true });
      }

      try {
        copyDirRecursive(src, dest);
      } catch (err) {
        console.error(`\n  Error installing ${skill}: ${err.message}\n`);
        process.exit(1);
      }
    }

    installed++;
  }

  console.log(`\n  Installed ${installed} Relay skills into:`);
  console.log(`    ${path.relative(process.cwd(), claudeDest)}/   (Claude Code)`);
  console.log(`    ${path.relative(process.cwd(), agentsDest)}/   (Codex CLI, Gemini CLI)`);

  if (skipped > 0) {
    console.log(`  Skipped ${skipped} (not found in package)`);
  }

  // Update context files
  const agentsStatus = appendContextFile(targetDir, "AGENTS.md");
  const geminiStatus = appendContextFile(targetDir, "GEMINI.md");

  console.log(`\n  Context files:`);
  console.log(`    AGENTS.md    ${agentsStatus}   (Codex CLI)`);
  console.log(`    GEMINI.md    ${geminiStatus}   (Gemini CLI)`);

  // Show next steps
  console.log(`
  Next steps:
    1. Open your AI coding CLI (Claude Code, Codex, or Gemini)
    2. Run /relay-setup to initialize the .relay/ data directory
    3. Run /relay-help to see what to do next

  Skills installed:`);

  for (const skill of RELAY_SKILLS) {
    const dest = path.join(claudeDest, skill);
    if (fs.existsSync(dest)) {
      console.log(`    /${skill}`);
    }
  }

  console.log("");
}

function uninstall(targetDir) {
  const claudeDest = path.join(targetDir, CLAUDE_SKILLS_DIR);
  const agentsDest = path.join(targetDir, AGENTS_SKILLS_DIR);

  // Refuse if uninstall target resolves to the source skills directory.
  // Without this, fs.rmSync(dest) inside the uninstall loop would
  // delete the source. Same structural bug as install() — symmetric
  // because uninstall() also does unconditional fs.rmSync(dest).
  const skillsSrc = path.join(__dirname, "..", CLAUDE_SKILLS_DIR);
  if (path.resolve(claudeDest) === path.resolve(skillsSrc)) {
    console.error(`\n  Error: uninstall target resolves to the source skills directory (${path.resolve(skillsSrc)}).\n  Refusing to uninstall — this would delete the source. Use a different target directory.\n`);
    process.exit(1);
  }

  let removed = 0;

  for (const skill of RELAY_SKILLS) {
    let found = false;
    for (const destBase of [claudeDest, agentsDest]) {
      const dest = path.join(destBase, skill);
      if (fs.existsSync(dest)) {
        fs.rmSync(dest, { recursive: true, force: true });
        found = true;
      }
    }
    if (found) removed++;
  }

  // Clean up context files
  removeContextSection(targetDir, "AGENTS.md");
  removeContextSection(targetDir, "GEMINI.md");

  if (removed > 0) {
    console.log(`\n  Removed ${removed} Relay skills from:`);
    console.log(`    ${path.relative(process.cwd(), claudeDest)}/`);
    console.log(`    ${path.relative(process.cwd(), agentsDest)}/`);
    console.log("  Cleaned relay sections from AGENTS.md and GEMINI.md");
    console.log("  Note: .relay/ data directory was NOT removed (your issues, features, and history are preserved)\n");
  } else {
    console.log("\n  No Relay skills found to remove.\n");
  }
}

// ────────────────────────────────────────────────────────────────────────
// /relay-auto hooks (optional, opt-in)
//
// 4 hooks that complement /relay-auto by surfacing active sessions on
// cold start (SessionStart), snapshotting state across compaction
// (PreCompact), and logging per-turn/per-subagent activity (Stop,
// SubagentStop). All implemented in a single Node runtime
// (relay-hook-runtime.js); the 8 shell wrappers are trivial.
//
// Hooks are opt-in via `npx relay-workflow install-hooks`. They are
// independent of Control's hooks — Claude Code's settings.json accepts
// multiple handlers per event, so both fire when both are installed.
// ────────────────────────────────────────────────────────────────────────

const HOOKS_SRC_DIR = ".claude/hooks";
const HOOK_RUNTIME = "relay-hook-runtime.js";
const RELAY_HOOK_FILES = [
  HOOK_RUNTIME,
  "relay-session-start.sh", "relay-session-start.ps1",
  "relay-pre-compact.sh",   "relay-pre-compact.ps1",
  "relay-subagent-stop.sh", "relay-subagent-stop.ps1",
  "relay-stop.sh",          "relay-stop.ps1",
];

// Maps Claude Code hook event name → wrapper script basename (no extension).
const HOOK_EVENT_TO_SCRIPT = {
  SessionStart: "relay-session-start",
  PreCompact:   "relay-pre-compact",
  SubagentStop: "relay-subagent-stop",
  Stop:         "relay-stop",
};

function detectHookRuntime() {
  // Detect bash availability (same heuristic Control uses). On Windows
  // without bash, fall back to PowerShell.
  try {
    const { execSync } = require("child_process");
    execSync("bash -c 'exit 0'", { stdio: "ignore", timeout: 2000 });
    return "bash";
  } catch {
    return "powershell";
  }
}

function buildHookCommand(scriptBase, runtime) {
  if (runtime === "bash") {
    return `bash -c 'cd "$CLAUDE_PROJECT_DIR" && exec bash .claude/hooks/${scriptBase}.sh'`;
  }
  // PowerShell — cwd-anchor via $env:CLAUDE_PROJECT_DIR.
  // Single-quote the inner -Command body so the outer shell (which may be bash
  // on Windows when Git Bash is present) does not expand $env as a bash var.
  return `powershell -NoProfile -Command 'Set-Location -LiteralPath $env:CLAUDE_PROJECT_DIR; & .claude\\hooks\\${scriptBase}.ps1'`;
}

function readSettingsJSON(settingsPath) {
  if (!fs.existsSync(settingsPath)) return {};
  try {
    return JSON.parse(fs.readFileSync(settingsPath, "utf8")) || {};
  } catch (err) {
    console.error(`\n  Error: ${settingsPath} is not valid JSON (${err.message}).`);
    console.error(`  Refusing to merge — fix the file manually, then re-run install-hooks.\n`);
    process.exit(1);
  }
}

function writeSettingsJSON(settingsPath, data) {
  fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
  // Atomic write: temp file + rename
  const tmp = settingsPath + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + "\n", "utf8");
  fs.renameSync(tmp, settingsPath);
}

function mergeRelayHookIntoSettings(settings, eventName, command) {
  // Claude Code settings shape:
  //   { "hooks": { "<EventName>": [ { "matcher": "...", "hooks": [ { "type": "command", "command": "..." } ] } ] } }
  // We append our entry idempotently (skip if our command string is already present).
  settings.hooks ||= {};
  settings.hooks[eventName] ||= [];

  const alreadyPresent = settings.hooks[eventName].some((group) =>
    Array.isArray(group.hooks) && group.hooks.some((h) => h && h.command === command)
  );
  if (alreadyPresent) return false;

  settings.hooks[eventName].push({
    matcher: "*",
    hooks: [{ type: "command", command }],
  });
  return true;
}

function removeRelayHookFromSettings(settings, eventName, scriptBase) {
  if (!settings.hooks || !Array.isArray(settings.hooks[eventName])) return false;

  // Remove any hook entry whose command references our script basename (matches
  // both bash and PowerShell variants, robust to path-style differences).
  const before = settings.hooks[eventName].length;
  settings.hooks[eventName] = settings.hooks[eventName]
    .map((group) => {
      if (!Array.isArray(group.hooks)) return group;
      return {
        ...group,
        hooks: group.hooks.filter((h) => !(h && typeof h.command === "string" && h.command.includes(scriptBase))),
      };
    })
    .filter((group) => Array.isArray(group.hooks) && group.hooks.length > 0);

  if (settings.hooks[eventName].length === 0) {
    delete settings.hooks[eventName];
  }
  if (Object.keys(settings.hooks).length === 0) {
    delete settings.hooks;
  }
  return settings.hooks?.[eventName]?.length !== before;
}

function installHooks(targetDir) {
  const hooksSrc = path.join(__dirname, "..", HOOKS_SRC_DIR);
  const hooksDest = path.join(targetDir, HOOKS_SRC_DIR);
  const settingsPath = path.join(targetDir, ".claude", "settings.json");

  // Refuse self-install (same pattern as install()/uninstall() to prevent
  // overwriting source-repo hooks when run from the dev tree).
  if (path.resolve(hooksDest) === path.resolve(hooksSrc)) {
    console.error(`\n  Error: install-hooks target resolves to the source hooks directory (${path.resolve(hooksSrc)}).\n  Refusing to install — this would overwrite the source. Use a different target directory.\n`);
    process.exit(1);
  }

  if (!fs.existsSync(hooksSrc)) {
    console.error("\n  Error: Relay hooks not found in package. Reinstall with: npm install relay-workflow\n");
    process.exit(1);
  }

  fs.mkdirSync(hooksDest, { recursive: true });

  // Copy hook scripts + runtime
  let copied = 0;
  for (const file of RELAY_HOOK_FILES) {
    const src = path.join(hooksSrc, file);
    const dst = path.join(hooksDest, file);
    if (!fs.existsSync(src)) {
      console.warn(`  Warning: ${file} not found in package, skipping`);
      continue;
    }
    fs.copyFileSync(src, dst);
    copied++;
  }

  // Wire into settings.json
  const runtime = detectHookRuntime();
  const settings = readSettingsJSON(settingsPath);
  let wired = 0;
  for (const [eventName, scriptBase] of Object.entries(HOOK_EVENT_TO_SCRIPT)) {
    const cmd = buildHookCommand(scriptBase, runtime);
    if (mergeRelayHookIntoSettings(settings, eventName, cmd)) wired++;
  }
  writeSettingsJSON(settingsPath, settings);

  console.log(`\n  Installed ${copied} hook file(s) into:`);
  console.log(`    ${path.relative(process.cwd(), hooksDest)}/`);
  console.log(`  Wired ${wired} hook event(s) into:`);
  console.log(`    ${path.relative(process.cwd(), settingsPath)}  (runtime: ${runtime})`);
  if (wired === 0) {
    console.log(`  (all hooks were already wired — nothing to do)`);
  }
  console.log(`\n  Hooks fire automatically from now on. To remove, run:`);
  console.log(`    npx relay-workflow uninstall-hooks\n`);
}

function uninstallHooks(targetDir) {
  const hooksDest = path.join(targetDir, HOOKS_SRC_DIR);
  const settingsPath = path.join(targetDir, ".claude", "settings.json");

  // Unwire from settings.json
  let unwired = 0;
  if (fs.existsSync(settingsPath)) {
    const settings = readSettingsJSON(settingsPath);
    for (const [eventName, scriptBase] of Object.entries(HOOK_EVENT_TO_SCRIPT)) {
      if (removeRelayHookFromSettings(settings, eventName, scriptBase)) unwired++;
    }
    writeSettingsJSON(settingsPath, settings);
  }

  // Remove hook scripts
  let removed = 0;
  if (fs.existsSync(hooksDest)) {
    for (const file of RELAY_HOOK_FILES) {
      const dst = path.join(hooksDest, file);
      if (fs.existsSync(dst)) {
        fs.unlinkSync(dst);
        removed++;
      }
    }
  }

  console.log(`\n  Removed ${removed} hook file(s) from ${path.relative(process.cwd(), hooksDest)}/`);
  console.log(`  Unwired ${unwired} hook event(s) from ${path.relative(process.cwd(), settingsPath)}`);
  console.log(`  Note: .relay/.auto-session/ session state is preserved.\n`);
}

function showHelp() {
  console.log(`
  relay-workflow v${VERSION}
  Persistent memory for AI coding workflows
  Works with: Claude Code, OpenAI Codex CLI, Google Gemini CLI

  Usage:
    npx relay-workflow install            Install Relay skills into current project
    npx relay-workflow uninstall          Remove Relay skills (keeps .relay/ data)
    npx relay-workflow install-hooks      Install optional /relay-auto hooks (SessionStart, PreCompact, SubagentStop, Stop)
    npx relay-workflow uninstall-hooks    Remove the /relay-auto hooks
    npx relay-workflow version            Show version
    npx relay-workflow help               Show this help

  What it does:
    Copies ${RELAY_SKILLS.length} skills into .claude/skills/relay-*/ and .agents/skills/relay-*/
    Updates AGENTS.md and GEMINI.md with skill references
    These skills give AI agents persistent memory across sessions.

  /relay-auto hooks (opt-in):
    SessionStart  — emit a marker on cold start if an auto-session is active
    PreCompact    — snapshot state.json + latest per-item summary before compaction
    SubagentStop  — append per-item agent activity to a JSONL audit log
    Stop          — append per-turn marker to a JSONL audit log
    Coexists with Control's hooks (Claude Code supports multiple handlers per event).

  After install:
    1. Open your AI coding CLI (Claude Code, Codex, or Gemini)
    2. Run /relay-setup to initialize
    3. (Optional) Run \`npx relay-workflow install-hooks\` to enable /relay-auto hooks
    4. Run /relay-help for guidance
  `);
}

// --- Main ---

const args = process.argv.slice(2);
const command = args[0] || "help";
const targetDir = args[1] || process.cwd();

switch (command) {
  case "install":
    console.log(`\n  relay-workflow v${VERSION} — installing...`);
    install(targetDir);
    break;

  case "uninstall":
  case "remove":
    console.log(`\n  relay-workflow v${VERSION} — uninstalling...`);
    uninstall(targetDir);
    break;

  case "install-hooks":
    console.log(`\n  relay-workflow v${VERSION} — installing /relay-auto hooks...`);
    installHooks(targetDir);
    break;

  case "uninstall-hooks":
    console.log(`\n  relay-workflow v${VERSION} — uninstalling /relay-auto hooks...`);
    uninstallHooks(targetDir);
    break;

  case "version":
  case "--version":
  case "-v":
    console.log(VERSION);
    break;

  case "help":
  case "--help":
  case "-h":
    showHelp();
    break;

  default:
    console.error(`\n  Unknown command: ${command}`);
    showHelp();
    process.exit(1);
}
